# Generated by Django 3.2 on 2021-04-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_sliderimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterModelOptions(
            name='categoryoptionvalue',
            options={'verbose_name_plural': 'خيارات المنتج'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name_plural': 'الخيارات المتاحة'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'الاحجام'},
        ),
        migrations.AlterModelOptions(
            name='sliderimages',
            options={'verbose_name_plural': 'صور الموقع'},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'verbose_name_plural': 'القيم المتاحة للخيارات'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='items',
        ),
    ]
