# Generated by Django 3.2 on 2021-04-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_items_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_confirmation_method',
            field=models.CharField(default='whatsapp', max_length=128),
            preserve_default=False,
        ),
    ]
