# Generated by Django 3.2 on 2021-04-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='fridge_status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
